import os

import configs as c

#get the best known fitness for the dataset
def getBest(name):
    try:
        bestFile = open(c.LIBS_PATH+"/best.tsp", "r")
    except OSError:
        pass
    
    for line in bestFile:
        if line.find(name) != -1:
            array = line.split(":")
            return int(array[1])

#print general information about the run
def printInformations(name,size,lk,id,n_best,new_pop,best_f):
    print(str(id)+" Generating population for problem "+name+" with population size "+str(size)+", using "+str(lk)+"% of LK generated tours and using:")
        
    if(new_pop==0):
        print("Cross using OX.\n")
    elif(new_pop==1):
        print("All vs All GPX2 crossover saving "+str(n_best)+" with reset population and roulete.\n")
    elif(new_pop==2):
        print("GPX2 with Ant Colony to introduce randomness.")
    else:
        print("All vs All GPX2 crossover saving "+str(n_best)+" with reset population and roulete.\n")


    print("best fitness found: "+str(best_f))
        
#erases the tours generated by LK
def eraseTours():
        for f in os.listdir("."):
            if f.endswith(".dat"):
                os.remove(f)