
Tour 1 - Sem ghost   
    cities.push_back(City(1, 0.0, 1.0));
    cities.push_back(City(4, 1.0, 1.0));
    cities.push_back(City(5, 1.0, 2.0));
    cities.push_back(City(2, 0.0, 2.0));
    cities.push_back(City(6, 1.0, 3.0));
    cities.push_back(City(8, 2.0, 3.0)); 
    cities.push_back(City(12, 2.0, 3.0));  
    cities.push_back(City(11, 3.0, 2.0));
    cities.push_back(City(14, 4.0, 2.0));  
    cities.push_back(City(13, 4.0, 1.0)); 
    cities.push_back(City(10, 3.0, 1.0));
    cities.push_back(City(9, 3.0, 0.0));  
    cities.push_back(City(7, 2.0, 0.0)); 
    cities.push_back(City(3, 1.0, 0.0));

    cities2.push_back(City(1, 0.0, 1.0));
    cities2.push_back(City(2, 0.0, 2.0));
    cities2.push_back(City(5, 1.0, 2.0));
    cities2.push_back(City(6, 1.0, 3.0));
    cities2.push_back(City(8, 2.0, 3.0)); 
    cities2.push_back(City(12, 2.0, 3.0));  
    cities2.push_back(City(14, 4.0, 2.0));  
    cities2.push_back(City(11, 3.0, 2.0));
    cities2.push_back(City(10, 3.0, 1.0));
    cities2.push_back(City(13, 4.0, 1.0)); 
    cities2.push_back(City(9, 3.0, 0.0));  
    cities2.push_back(City(7, 2.0, 0.0)); 
    cities2.push_back(City(3, 1.0, 0.0));
    cities2.push_back(City(4, 1.0, 1.0));

Tour 1 - Com ghost
    cities.push_back(City(1, 0.0, 1.0));
    cities.push_back(City(4, 1.0, 1.0));
    cities.push_back(City(5, 1.0, 2.0));
    cities.push_back(City(2, 0.0, 2.0));
    cities.push_back(City(8, 2.0, 3.0));  
    cities.push_back(City(11, 3.0, 2.0));
    cities.push_back(City(14, 4.0, 2.0));  
    cities.push_back(City(13, 4.0, 1.0)); 
    cities.push_back(City(10, 3.0, 1.0));
    cities.push_back(City(9, 3.0, 0.0));  
    cities.push_back(City(7, 2.0, 0.0)); 
    cities.push_back(City(3, 1.0, 0.0));

    cities2.push_back(City(1, 0.0, 1.0));
    cities2.push_back(City(2, 0.0, 2.0));
    cities2.push_back(City(5, 1.0, 2.0));
    cities2.push_back(City(8, 2.0, 3.0));  
    cities2.push_back(City(14, 4.0, 2.0));  
    cities2.push_back(City(11, 3.0, 2.0));
    cities2.push_back(City(10, 3.0, 1.0));
    cities2.push_back(City(13, 4.0, 1.0)); 
    cities2.push_back(City(9, 3.0, 0.0));  
    cities2.push_back(City(7, 2.0, 0.0)); 
    cities2.push_back(City(3, 1.0, 0.0));
    cities2.push_back(City(4, 1.0, 1.0));

Kapriel Tour - Partição não recombinante

    cities.push_back(City(1, 0.0, 0.0));
    cities.push_back(City(2, 0.0, -1.0));
    cities.push_back(City(4, 1.0, -1.0)); 
    cities.push_back(City(6, 2.0, 1.0));
    cities.push_back(City(7, 3.0, 0.0));  
    cities.push_back(City(9, 4.0, 0.0));
    cities.push_back(City(12, 5.0, -1.0));
    cities.push_back(City(11, 5.0, 0.0)); 
    cities.push_back(City(10, 4.0, -1.0)); 
    cities.push_back(City(8, 3.0, -1.0));  
    cities.push_back(City(5, 2.0, 0.0)); 
    cities.push_back(City(3, 1.0, 0.0));

    cities2.push_back(City(1, 0.0, 0.0));
    cities2.push_back(City(4, 1.0, -1.0)); 
    cities2.push_back(City(6, 2.0, 1.0));
    cities2.push_back(City(8, 3.0, -1.0)); 
    cities2.push_back(City(10, 4.0, -1.0));  
    cities2.push_back(City(12, 5.0, -1.0));
    cities2.push_back(City(11, 5.0, 0.0)); 
    cities2.push_back(City(9, 4.0, 0.0));
    cities2.push_back(City(7, 3.0, 0.0));  
    cities2.push_back(City(5, 2.0, 0.0)); 
    cities2.push_back(City(3, 1.0, 0.0));
    cities2.push_back(City(2, 0.0, -1.0));

Tour Noda feliz
    
    cities.push_back(City(1, 0.0, 4.0));
    cities.push_back(City(2, 3.0, 4.0));
    cities.push_back(City(3, 4.0, 3.0)); 
    cities.push_back(City(4, 3.0, 3.0));
    cities.push_back(City(5, 2.0, 3.0));  
    cities.push_back(City(6, 1.0, 2.0));
    cities.push_back(City(7, 2.0, 1.0));
    cities.push_back(City(8, 3.0, 1.0)); 
    cities.push_back(City(9, 3.0, 0.0)); 
    cities.push_back(City(10, 0.0, 0.0));

    cities2.push_back(City(1, 0.0, 4.0));
    cities2.push_back(City(2, 3.0, 4.0));
    cities2.push_back(City(4, 3.0, 3.0));
    cities2.push_back(City(5, 2.0, 3.0)); 
    cities2.push_back(City(7, 2.0, 1.0));
    cities2.push_back(City(8, 3.0, 1.0));  
    cities2.push_back(City(3, 4.0, 3.0)); 
    cities2.push_back(City(9, 3.0, 0.0)); 
    cities2.push_back(City(10, 0.0, 0.0));
    cities2.push_back(City(6, 1.0, 2.0));