import os

import configs as c

#get the best known fitness for the dataset
def getBest(name):
    try:
        bestFile = open(c.LIBS_PATH+"/best.tsp", "r")
    except OSError:
        pass
    
    for line in bestFile:
        if line.find(name) != -1:
            array = line.split(":")
            return int(array[1])

#print general information about the run
def printInformations(name,id,best):
    print(str(id)+" Generating population for problem "+name+" with population size "+str(c.POP_SIZE)+", using "+str(c.LK_PERCENTAGE*100)+"% of LK generated tours and using:")
        
    if(c.NEW_POP_TYPE==0):
        print("All vs All GPX2 crossover\n")
    elif(c.NEW_POP_TYPE==1):
        print(str(c.N_BEST)+" best vs All GPX2 crossover with reset population\n")
    else:
        print("All vs ALL with "+str(c.N_BEST)+" best saved to the next population and the rest reseted\n")
        
    print("best fitness found: "+str(best))
        
#erases the tours generated by LK
def eraseTours():
        for f in os.listdir("."):
            if f.endswith(".dat"):
                os.remove(f)